/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as DeliveryIndexRouteImport } from './routes/delivery.index'
import { Route as DeliveryRestaurantIdRouteImport } from './routes/delivery.$restaurantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/delivery/',
  path: '/delivery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRestaurantIdRoute = DeliveryRestaurantIdRouteImport.update({
  id: '/delivery/$restaurantId',
  path: '/delivery/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/profissionais': typeof ProfissionaisRoute
  '/vitrine': typeof VitrineRoute
  '/delivery/$restaurantId': typeof DeliveryRestaurantIdRoute
  '/delivery/': typeof DeliveryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/profissionais': typeof ProfissionaisRoute
  '/vitrine': typeof VitrineRoute
  '/delivery/$restaurantId': typeof DeliveryRestaurantIdRoute
  '/delivery': typeof DeliveryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/profissionais': typeof ProfissionaisRoute
  '/vitrine': typeof VitrineRoute
  '/delivery/$restaurantId': typeof DeliveryRestaurantIdRoute
  '/delivery/': typeof DeliveryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/profissionais'
    | '/vitrine'
    | '/delivery/$restaurantId'
    | '/delivery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/profissionais'
    | '/vitrine'
    | '/delivery/$restaurantId'
    | '/delivery'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/profissionais'
    | '/vitrine'
    | '/delivery/$restaurantId'
    | '/delivery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  VitrineRoute: typeof VitrineRoute
  DeliveryRestaurantIdRoute: typeof DeliveryRestaurantIdRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/delivery'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/$restaurantId': {
      id: '/delivery/$restaurantId'
      path: '/delivery/$restaurantId'
      fullPath: '/delivery/$restaurantId'
      preLoaderRoute: typeof DeliveryRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  VitrineRoute: VitrineRoute,
  DeliveryRestaurantIdRoute: DeliveryRestaurantIdRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
